shynet/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("dashboard/", views.DashboardApiView.as_view(), name="services"),
]

shynet/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("service/new/", views.ServiceCreateView.as_view(), name="service_create"),
    path("service/<pk>/", views.ServiceView.as_view(), name="service"),
    path(
        "service/<pk>/manage/",
        views.ServiceUpdateView.as_view(),
        name="service_update",
    ),
    path(
        "service/<pk>/delete/",
        views.ServiceDeleteView.as_view(),
        name="service_delete",
    ),
    path(
        "service/<pk>/sessions/",
        views.ServiceSessionsListView.as_view(),
        name="service_session_list",
    ),
    path(
        "service/<pk>/sessions/<session_pk>/",
        views.ServiceSessionView.as_view(),
        name="service_session",
    ),
    path(
        "api-token-refresh/",
        views.RefreshApiTokenView.as_view(),
        name="api_token_refresh",
    ),
]

shynet/shynet/urls.py
from django.contrib import admin
from django.urls import include, path
import debug_toolbar

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("ingress/", include(("analytics.ingress_urls", "ingress")), name="ingress"),
    path("dashboard/", include(("dashboard.urls", "dashboard"), namespace="dashboard")),
    path("healthz/", include("health_check.urls")),
    path("", include(("core.urls", "core"), namespace="core")),
    path("api/v1/", include(("api.urls", "api"), namespace="api")),
]

shynet/analytics/models.py
import uuid

from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.models import Service, ACTIVE_USER_TIMEDELTA


def _default_uuid():
    return str(uuid.uuid4())


class Session(models.Model):
    uuid = models.UUIDField(default=_default_uuid, primary_key=True)
    service = models.ForeignKey(
        Service, verbose_name=_("Service"), on_delete=models.CASCADE, db_index=True
    )

    # Cross-session identification; optional, and provided by the service
    identifier = models.TextField(
        blank=True, db_index=True, verbose_name=_("Identifier")
    )

    # Time
    start_time = models.DateTimeField(
        default=timezone.now, db_index=True, verbose_name=_("Start time")
    )
    last_seen = models.DateTimeField(
        default=timezone.now, db_index=True, verbose_name=_("Last seen")
    )

    # Core request information
    user_agent = models.TextField(verbose_name=_("User agent"))
    browser = models.TextField(verbose_name=_("Browser"))
    device = models.TextField(verbose_name=_("Device"))
    device_type = models.CharField(
        max_length=7,
        choices=[
            ("PHONE", _("Phone")),
            ("TABLET", _("Tablet")),
            ("DESKTOP", _("Desktop")),
            ("ROBOT", _("Robot")),
            ("OTHER", _("Other")),
        ],
        default="OTHER",
        verbose_name=_("Device type"),
    )
    os = models.TextField(verbose_name=_("OS"))
    ip = models.GenericIPAddressField(db_index=True, null=True, verbose_name=_("IP"))

    # GeoIP data
    asn = models.TextField(blank=True, verbose_name=_("Asn"))
    country = models.TextField(blank=True, verbose_name=_("Country"))
    longitude = models.FloatField(null=True, verbose_name=_("Longitude"))
    latitude = models.FloatField(null=True, verbose_name=_("Latitude"))
    time_zone = models.TextField(blank=True, verbose_name=_("Time zone"))

    is_bounce = models.BooleanField(
        default=True, db_index=True, verbose_name=_("Is bounce")
    )

    class Meta:
        verbose_name = _("Session")
        verbose_name_plural = _("Sessions")
        ordering = ["-start_time"]
        indexes = [
            models.Index(fields=["service", "-start_time"]),
            models.Index(fields=["service", "-last_seen"]),
            models.Index(fields=["service", "identifier"]),
        ]

    @property
    def is_currently_active(self):
        return timezone.now() - self.last_seen < ACTIVE_USER_TIMEDELTA

    @property
    def duration(self):
        return self.last_seen - self.start_time

    def __str__(self):
        return f"{self.identifier if self.identifier != '' else 'Anonymous'} @ {self.service.name} [{str(self.uuid)[:6]}]"

    def get_absolute_url(self):
        return reverse(
            "dashboard:service_session",
            kwargs={"pk": self.service.pk, "session_pk": self.uuid},
        )

    def recalculate_bounce(self):
        bounce = self.hit_set.count() == 1
        if bounce != self.is_bounce:
            self.is_bounce = bounce
            self.save()


class Hit(models.Model):
    session = models.ForeignKey(
        Session, on_delete=models.CASCADE, db_index=True, verbose_name=_("Session")
    )
    initial = models.BooleanField(default=True, db_index=True)

    # Base request information
    start_time = models.DateTimeField(default=timezone.now, db_index=True)
    last_seen = models.DateTimeField(default=timezone.now, db_index=True)
    heartbeats = models.IntegerField(default=0)
    tracker = models.TextField(
        choices=[("JS", "JavaScript"), ("PIXEL", "Pixel (noscript)")]
    )  # Tracking pixel or JS

    # Advanced page information
    location = models.TextField(blank=True, db_index=True)
    referrer = models.TextField(blank=True, db_index=True)
    load_time = models.FloatField(null=True, db_index=True)

    # While not necessary, we store the root service directly for performance.
    # It makes querying much easier; no need for inner joins.
    service = models.ForeignKey(Service, on_delete=models.CASCADE, db_index=True)

    class Meta:
        verbose_name = _("Hit")
        verbose_name_plural = _("Hits")
        ordering = ["-start_time"]
        indexes = [
            models.Index(fields=["session", "-start_time"]),
            models.Index(fields=["service", "-start_time"]),
            models.Index(fields=["session", "location"]),
            models.Index(fields=["session", "referrer"]),
        ]

    @property
    def duration(self):
        return self.last_seen - self.start_time

    def get_absolute_url(self):
        return reverse(
            "dashboard:service_session",
            kwargs={"pk": self.service.pk, "session_pk": self.session.pk},
        )

shynet/dashboard/forms.py
from allauth.account.admin import EmailAddress
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from core.models import Service, User


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = [
            "name",
            "link",
            "respect_dnt",
            "collect_ips",
            "ignored_ips",
            "ignore_robots",
            "hide_referrer_regex",
            "origins",
            "collaborators",
            "script_inject",
        ]
        widgets = {
            "name": forms.TextInput(),
            "origins": forms.TextInput(),
            "ignored_ips": forms.TextInput(),
            "respect_dnt": forms.RadioSelect(
                choices=[(True, _("Yes")), (False, _("No"))]
            ),
            "collect_ips": forms.RadioSelect(
                choices=[(True, _("Yes")), (False, _("No"))]
            ),
            "ignore_robots": forms.RadioSelect(
                choices=[(True, _("Yes")), (False, _("No"))]
            ),
            "hide_referrer_regex": forms.TextInput(),
            "script_inject": forms.Textarea(attrs={"class": "font-mono", "rows": 5}),
        }
        labels = {
            "origins": _("Allowed origins"),
            "respect_dnt": _("Respect DNT"),
            "ignored_ips": _("Ignored IP addresses"),
            "ignore_robots": _("Ignore robots"),
            "hide_referrer_regex": _("Hide specific referrers"),
            "script_inject": _("Additional injected JS"),
        }
        help_texts = {
            "name": _("What should the service be called?"),
            "link": _("What's the service's primary URL?"),
            "origins": _(
                "At what origins does the service operate? Use commas to separate multiple values. This sets CORS headers, so use '*' if you're not sure (or don't care)."
            ),
            "respect_dnt": _(
                "Should visitors who have enabled <a href='https://en.wikipedia.org/wiki/Do_Not_Track'>Do Not Track</a> be excluded from all data?"
            ),
            "ignored_ips": _(
                "A comma-separated list of IP addresses or IP ranges (IPv4 and IPv6) to exclude from tracking (e.g., '192.168.0.2, 127.0.0.1/32')."
            ),
            "ignore_robots": _(
                "Should sessions generated by bots be excluded from tracking?"
            ),
            "hide_referrer_regex": _(
                "Any referrers that match this <a href='https://regexr.com/'>RegEx</a> will not be listed in the referrer summary. Sessions will still be tracked normally. No effect if left blank."
            ),
            "script_inject": _(
                "Optional additional JavaScript to inject at the end of the Shynet script. This code will be injected on every page where this service is installed."
            ),
        }

    collect_ips = forms.BooleanField(
        help_text=_("IP address collection is disabled globally by your administrator.")
        if settings.BLOCK_ALL_IPS
        else _(
            "Should individual IP addresses be collected? IP metadata (location, host, etc) will still be collected."
        ),
        widget=forms.RadioSelect(choices=[(True, _("Yes")), (False, _("No"))]),
        initial=False if settings.BLOCK_ALL_IPS else True,
        required=False,
        disabled=settings.BLOCK_ALL_IPS,
    )

    def clean_collect_ips(self):
        collect_ips = self.cleaned_data["collect_ips"]
        # Forces collect IPs to be false if it is disabled globally
        return False if settings.BLOCK_ALL_IPS else collect_ips

    collaborators = forms.CharField(
        help_text=_(
            "Which users on this Shynet instance should have read-only access to this service? (Comma separated list of emails.)"
        ),
        required=False,
    )

    def clean_collaborators(self):
        collaborators = []
        users_to_emails = (
            {}
        )  # maps users to the email they are listed under as a collaborator
        for collaborator_email in self.cleaned_data["collaborators"].split(","):
            email = collaborator_email.strip()
            if email == "":
                continue
            collaborator_email_linked = EmailAddress.objects.filter(
                email__iexact=email
            ).first()
            if collaborator_email_linked is None:
                raise forms.ValidationError(f"Email '{email}' is not registered")
            user = collaborator_email_linked.user
            if user in collaborators:
                raise forms.ValidationError(
                    f"The emails '{email}' and '{users_to_emails[user]}' both correspond to the same user"
                )
            users_to_emails[user] = email
            collaborators.append(collaborator_email_linked.user)
        return collaborators

    def get_initial_for_field(self, field, field_name):
        initial = super(ServiceForm, self).get_initial_for_field(field, field_name)
        if field_name == "collaborators":
            return ", ".join([user.email for user in (initial or [])])
        return initial

shynet/dashboard/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.cache import cache
from django.db.models import Q
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)
from rules.contrib.views import PermissionRequiredMixin

from analytics.models import Session
from core.models import Service, _default_api_token

from .forms import ServiceForm
from .mixins import DateRangeMixin


class DashboardView(LoginRequiredMixin, DateRangeMixin, ListView):
    model = Service
    template_name = "dashboard/pages/dashboard.html"
    paginate_by = settings.DASHBOARD_PAGE_SIZE

    def get_queryset(self):
        return Service.objects.filter(
            Q(owner=self.request.user) | Q(collaborators__in=[self.request.user])
        ).distinct()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        for service in data["object_list"]:
            service.stats = service.get_core_stats(
                self.get_start_date(), self.get_end_date()
            )

        return data


class ServiceCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    template_name = "dashboard/pages/service_create.html"
    permission_required = "core.create_service"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("dashboard:service", kwargs={"pk": self.object.uuid})


class ServiceView(
    LoginRequiredMixin, PermissionRequiredMixin, DateRangeMixin, DetailView
):
    model = Service
    template_name = "dashboard/pages/service.html"
    permission_required = "core.view_service"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["script_protocol"] = "https://" if settings.SCRIPT_USE_HTTPS else "http://"
        data["stats"] = self.object.get_core_stats(data["start_date"], data["end_date"])
        data["object_list"] = Session.objects.filter(
            service=self.get_object(),
            start_time__lt=self.get_end_date(),
            start_time__gt=self.get_start_date(),
        ).order_by("-start_time")[:10]
        return data


class ServiceUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Service
    form_class = ServiceForm
    template_name = "dashboard/pages/service_update.html"
    permission_required = "core.change_service"
    success_message = "Your changes were saved successfully."

    def get_success_url(self):
        return reverse("dashboard:service", kwargs={"pk": self.object.uuid})

    def form_valid(self, *args, **kwargs):
        resp = super().form_valid(*args, **kwargs)
        cache.set(
            f"service_origins_{self.object.uuid}", self.object.origins, timeout=3600
        )
        cache.set(
            f"script_inject_{self.object.uuid}", self.object.script_inject, timeout=3600
        )
        return resp

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        data["script_protocol"] = "https://" if settings.SCRIPT_USE_HTTPS else "http://"
        return data


class ServiceDeleteView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, DeleteView
):
    model = Service
    form_class = ServiceForm
    template_name = "dashboard/pages/service_delete.html"
    permission_required = "core.delete_service"
    success_message = "The service was deleted successfully."

    def get_success_url(self):
        return reverse("dashboard:dashboard")


class ServiceSessionsListView(
    LoginRequiredMixin, PermissionRequiredMixin, DateRangeMixin, ListView
):
    model = Session
    template_name = "dashboard/pages/service_session_list.html"
    paginate_by = 20
    permission_required = "core.view_service"

    def get_object(self):
        return get_object_or_404(Service, pk=self.kwargs.get("pk"))

    def get_queryset(self):
        return Session.objects.filter(
            service=self.get_object(),
            start_time__lt=self.get_end_date(),
            start_time__gt=self.get_start_date(),
        ).order_by("-start_time")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["object"] = self.get_object()
        return data


class ServiceSessionView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Session
    template_name = "dashboard/pages/service_session.html"
    pk_url_kwarg = "session_pk"
    context_object_name = "session"
    permission_required = "core.view_service"

    def get_permission_object(self, **kwargs):
        return self.get_object().service

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["object"] = get_object_or_404(Service, pk=self.kwargs.get("pk"))
        return data


class RefreshApiTokenView(LoginRequiredMixin, View):
    def post(self, request):
        request.user.api_token = _default_api_token()
        request.user.save()
        return redirect("account_change_password")

shynet/dashboard/templates/dashboard/pages/dashboard.html
{% extends "base.html" %}

{% load i18n rules pagination %}

{% block content %}
<div class="md:flex justify-between items-center">
    <div class="flex-1 truncate display-none md:display-block mr-4 md:mb-0 mb-4" title="{{request.site.name|default:"Dashboard"}}">
        <h4 class="heading truncate">{{request.site.name|default:"Dashboard"}}</h4>
    </div>
    <div class="flex items-center">
        <div class="mr-1">
            {% include 'dashboard/includes/date_range.html' %}
        </div>
        {% has_perm "core.create_service" user as can_create %}
        {% if can_create %}
        <a href="{% url 'dashboard:service_create' %}" class="button field !low bg-neutral-000 w-auto">+ {% trans 'New Service' %}</a>
        {% endif %}
    </div>
</div>
<hr class="sep h-8 md:h-12">
{% for object in object_list|dictsortreversed:"stats.session_count" %}
{% include 'dashboard/includes/service_overview.html' %}
{% empty %}
<p class="aside ~urge !high">You don't have any services yet. {% if can_create %}Get started by <a href="{% url 'dashboard:service_create' %}" class="underline">creating one</a>.{% endif %}</p>
{% endfor %}

{% if object_list %}
{% pagination page_obj request %}
{% endif %}

{% endblock %}

shynet/dashboard/templates/dashboard/pages/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section class="content">
    <h2>{{request.site.name}} {% trans 'Analytics' %}</h2>
    <p>{{request.site.name}} uses Shynet. Eventually, more information about Shynet will be available here.</p>
    <a href="{% url 'account_login' %}" class="button ~urge !high">{% trans 'Log In' %}</a>
</section>
{% endblock %}

shynet/dashboard/templates/dashboard/pages/service_create.html
{% extends "base.html" %}

{% load i18n a17t_tags %}

{% block head_title %}{% trans 'Create Service' %}{% endblock %}

{% block content %}
<h4 class="heading leading-none">{% trans 'Create Service' %}</h4>
<hr class="sep">
<form class="card ~neutral !low p-0 max-w-xl" method="POST">
    {% csrf_token %}
    <div class="p-4">
        {% include 'dashboard/includes/service_form.html' %}
    </div>
    <div class="section ~urge !normal p-4">
        <button type="submit" class="button ~urge !high">{% trans 'Create' %}</button>
        <a href="{% url 'dashboard:dashboard' %}" class="button ~urge !low">{% trans 'Cancel' %}</a>
    </div>
</form>
{% endblock %}

shynet/dashboard/templates/dashboard/pages/service_delete.html
{% extends "dashboard/service_base.html" %}

{% load i18n a17t_tags %}

{% block head_title %}{% trans 'Delete' %} {{object.name}}{% endblock %}

{% block service_content %}
<form class="card ~neutral !low p-0 max-w-xl" method="POST">
    {% csrf_token %}
    <div class="p-4">
        <p>
            {% blocktrans trimmed %}
                Are you sure you want to delete this service? All of its
                analytics and associated data will be permanently deleted.
            {% endblocktrans %}
        </p>
        {{form|a17t}}
    </div>
    <div class="section ~critical !normal p-4">
        <button type="submit" class="button ~critical !high">Delete</button>
        <a href="{% url 'dashboard:service' object.uuid %}" class="button ~critical !low">Cancel</a>
    </div>
</form>
{% endblock %}

shynet/dashboard/templates/dashboard/pages/service_session.html
{% extends "dashboard/service_base.html" %}

{% load i18n a17t_tags pagination humanize helpers %}

{% block head_title %}{{object.name}} Session{% endblock %}

{% block service_actions %}
<a href="{% contextual_url 'dashboard:service' object.uuid %}" class="button field !low bg-neutral-000 w-auto">Analytics &rarr;</a>
{% endblock %}

{% block service_content %}
<article class="card ~neutral !high">
    <div class="md:flex items-center justify-between">
        <div>
            <h3 class="heading text-2xl mr-4">
                {{session.identifier|default:"Anonymous"}}, {{session.duration|naturaldelta}}
            </h3>
        </div>
        <div>
            <p class="font-medium text-lg">{{session.start_time|date:"M j Y, g:i a"}} to
                {{session.last_seen|date:"g:i a"}}{% if session.is_currently_active %} <span class="chip ~positive !high text-base">Online</span>{% endif %}</p>
        </div>
    </div>
    <hr class="sep h-8 md:h-12">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-gray-400 font-medium">
        <div>
            <p>{% trans 'Browser' %}</p>
            <p class="label">{{session.browser|default:"Unknown"}}</p>
        </div>
        <div>
            <p>{% trans 'Device' %}</p>
            <p class="label">{{session.device|default:"Unknown"}}</p>
        </div>
        <div>
            <p{% trans 'Device Type' %}</p>
            <p class="label">{{session.device_type|title}}</p>
        </div>
        <div>
            <p>{% trans 'OS' %}</p>
            <p class="label">{{session.os|default:"Unknown"}}</p>
        </div>
        <div>
            <p>{% trans 'Network' %}</p>
            <p class="label">{{session.asn|default:"Unknown"}}</p>
        </div>
        <div>
            <p>{% trans 'Country' %}</p>
            <p class="label"><span class="{{session.country|flag_class}}"></span>{{session.country|country_name}}</p>
        </div>
        <div>
            <p>{% trans 'Location' %}</p>
            <p class="label">
                {% if session.latitude %}
                <a href="{{session|location_url}}" target="_blank">{% trans 'Open in Maps' %} &nearr;</a>
                {% else %}
                {% trans 'Unknown' %}
                {% endif %}
            </p>
        </div>
        <div>
            <p>IP</p>
            <p class="label" title="{{session.ip}}">{{session.ip|default:"Not Collected"|truncatechars:"16"}}</p>
        </div>
    </div>
</article>
<div class="">
    {% for hit in session.hit_set.all %}
    <article class="my-12 md:flex">
        <div class="md:w-2/12 mb-2 md:mr-4 pt-4 md:text-right">
            <div class="text-lg font-medium">{{hit.start_time|date:"g:i a"}}</div>
        </div>
        <div class="md:flex card ~neutral !low flex-grow justify-between">
            <div class="mb-4 md:mb-0 md:w-1/2">
                <p class="label font-medium text-lg truncate">{{hit.location|default:"Unknown"|urlize}}</p>
                {% if hit.referrer %}
                <p>via {{hit.referrer|urlize}}<p>
                {% endif %}
            </div>
            <div class="grid grid-cols-3 gap-3 md:pl-8 md:w-1/2">
                <div>
                    <p>{% trans 'Duration' %}</p>
                    <p class="label">{{hit.duration|naturaldelta}}</p>
                </div>
                <div>
                    <p>{% trans 'Load' %}</p>
                    <p class="label">{{hit.load_time|floatformat:"0"}}ms</p>
                </div>
                <div>
                    <p>{% trans 'Tracker' %}</p>
                    <p class="label">{{hit.tracker}}</p>
                </div>
            </div>
            <div>
    </article>
    {% endfor %}
</div>
{% endblock %}

shynet/dashboard/templates/dashboard/pages/service_session_list.html
{% extends "dashboard/service_base.html" %}

{% load i18n a17t_tags pagination humanize helpers %}

{% block head_title %}{{object.name}} {% trans 'Sessions' %}{% endblock %}

{% block service_actions %}
<div class="mr-2">{% include 'dashboard/includes/date_range.html' %}</div>
<a href="{% contextual_url 'dashboard:service' object.uuid %}" class="button field ~neutral !low bg-neutral-000 w-auto">{% trans 'Analytics' %} &rarr;</a>
{% endblock %}

{% block service_content %}
<div class="card ~neutral !low mb-8 pt-2 max-w-full overflow-x-auto">
    {% include 'dashboard/includes/session_list.html' %}
</div>
{% pagination page_obj request %}
{% endblock %}

shynet/dashboard/templates/dashboard/pages/service_update.html
{% extends "dashboard/service_base.html" %}

{% load i18n a17t_tags %}

{% block head_title %}{{object.name}} {% trans 'Management' %}{% endblock %}

{% block service_actions %}
<a href="{% url 'dashboard:service' object.uuid %}" class="button field !low bg-neutral-000 w-auto">{% trans 'View' %} &rarr;</a>
{% endblock %}

{% block service_content %}
<div class="max-w-xl content">
    <h5>{% trans 'Installation'  %}</h5>
    <p>
        {% blocktrans trimmed %}
        Place the following snippet at the end of the <code>&lt;body&gt;</code> tag on any page you'd like to track.
        {% endblocktrans %}
    </p>
    {% include 'dashboard/includes/service_snippet.html' %}
    <hr class="sep h-4">
    <h5>{% trans 'Settings' %}</h5>
    <form class="card ~neutral !low p-0" method="POST">
        {% csrf_token %}
        <div class="p-4">
            {% include 'dashboard/includes/service_form.html' %}
        </div>
        <div class="section ~neutral !normal p-4 flex justify-between">
            <div>
                <button type="submit" class="button ~neutral !high">{% trans 'Save' %}</button>
                <a href="{% url 'dashboard:service' object.uuid %}" class="button ~neutral !low">{% trans 'Cancel' %}</a>
            </div>
            <div>
                <a href="{% url 'dashboard:service_delete' object.uuid %}" class="button ~critical !high">{% trans 'Delete' %}</a>
            </div>
        </div>
    </form>
    <hr class="sep h-4">
    <h5>API</h5>
    <div class="card ~neutral !low content">
        <p>Shynet provides a simple API that you can use to pull data programmatically. You can access this data via this URL:</p>
        <code class="text-sm">{{script_protocol}}{{request.get_host}}{% url 'api:services' %}?uuid={{object.uuid}}</code>
        <p>
        There are 2 optional query parameters:
        <ul>
            <li><code class="text-sm">startDate</code> &mdash; to set the start date (in format YYYY-MM-DD)</li>
            <li><code class="text-sm">endDate</code> &mdash; to set the end date (in format YYYY-MM-DD)</li>
        </ul>
        </p>
        <p>Example using cURL:</p>
        <code class="text-sm">curl -H 'Authorization: Token (your API token, available on security page)' '{{script_protocol}}{{request.get_host}}{% url 'api:services' %}?uuid={{object.uuid}}&startDate=2021-01-01&endDate=2050-01-01'</code>
    </div>
</div>
{% endblock %}